import { StyleSheet, View } from 'react-native';

export const loginstyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E0F7FA',
    padding: 15,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 20,
  },
  logo: {
    width: 150,
    height: 90,
  },
  cardContainer: {
    backgroundColor: '#F0F4C3',
    borderRadius: 10,
    padding: 15,
    width: '100%',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  welcomeContainer: {
    marginTop: 20,
    marginBottom: 20,
    alignItems: 'center',
  },
  welcomeText: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#303481',
    textAlign: 'center',
    lineHeight: 45,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  subtitleText: {
    fontSize: 14,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 16,
  },
  form: {
    width: '100%',
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    paddingHorizontal: 15,
  },
  countryCode: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333333',
    marginRight: 10,
    backgroundColor: '#f8f8f8',
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  inputWrapper: {
    flex: 1,
  },
  input: {
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    color: '#333',
  },
  errorText: {
    color: '#dc3545',
    fontSize: 12,
    marginTop: 4,
    textAlign: 'center',
    marginBottom: 10,
  },
  successText: {
    color: '#28a745',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 16,
  },
  button: {
    backgroundColor: '#303481',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    marginTop: 20,
    width: '100%',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  attemptText: {
    color: '#dc3545',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 16,
  },
  keypadContainer: {
    marginTop: 12,
    marginBottom: 12,
    paddingHorizontal: 10,
  },
  keypadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  numericButton: {
    backgroundColor: '#303481',
    width: '28%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    elevation: 2,
  },
  numericButtonText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '500',
  },
  loginButton: {
    backgroundColor: '#28a745',
  },
  loginButtonText: {
    fontSize: 28,
  },
});

export const blockstyle = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    backgroundColor: "#E0F7FA",
  },
  card: {
    backgroundColor: "#F0F4C3",
    padding: 24,
    borderRadius: 16,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
  },
  noteText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 16,
    textAlign: 'center',
  },
  messageText: {
    fontSize: 18,
    textAlign: 'center',
    marginBottom: 32,
    color: "#444",
    lineHeight: 24,
    paddingHorizontal: 10,
  },
  button: {
    height: 50,
    backgroundColor: "#3467eb",
    justifyContent: "center",
    alignItems: "center", 
    borderRadius: 25,
    width: 150,
    shadowColor: "#3467eb",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 5,
  },
  buttonText: {
    color: "#fff", 
    fontSize: 18,
    fontWeight: "bold",
  },
});

export const pinstyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E0F7FA',
    padding: 20,
    alignItems: 'center',
  },
  headerText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#303481',
    marginTop: 15,
    marginBottom: 20,
  },
  phoneContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 40,
    gap: 10,
  },
  phoneText: {
    fontSize: 18,
    color: '#303481',
    fontWeight: '500',
  },
  pinContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 15,
    marginBottom: 40,
  },
  pinInput: {
    width: 55,
    height: 55,
    borderWidth: 2,
    borderColor: '#303481',
    borderRadius: 15,
    fontSize: 26,
    textAlign: 'center',
    backgroundColor: '#fff',
    elevation: 3,
  },
  keypadContainer: {
    width: '85%',
    alignItems: 'center',
    marginTop: 20,
    gap: 20,
  },
  keypadRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    width: '100%',
  },
  keypadButton: {
    width: 75,
    aspectRatio: 1,
    backgroundColor: '#303481',
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  keypadButtonText: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
  },
  errorText: {
    color: '#dc3545',
    fontSize: 12,
    marginTop: 5,
    fontWeight: '500',
  },
  attemptText: {
    color: '#dc3545',
    fontSize: 10,
    marginTop: 15,
    fontWeight: '500',
  },
  backButton: {
    backgroundColor: '#fff',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#303481',
    elevation: 2,
  },
  backButtonText: {
    color: '#303481',
    fontSize: 14,
    fontWeight: '600',
  },
});

// Add a default export component
export default function MobileStyles() {
  return <View />;
}
